export enum ValueType {
    Uint32 = 0,
    Int32 = 1,
    Float32 = 2,
    Float64 = 3,
    Boolean = 4,
    String = 5,
    Pointer = 6,
    MeshAttributeMeshIndex = 7,
    MeshAttributeStructPointer = 8,
    IndexDataStructPointer = 9,
    IndexDataPointer = 10,
    PointerFree = 11,
    PointerAlloc = 12,
    PointerAllocSize = 13,
    PointerAllocEnd = 14,
    PointerTemp = 15,
    Void = 16,
    PointerPreStart = 128,
    PointerPreEnd = 255,
};